<?php

namespace AppBundle\Repository;

/**
 * CoinDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoinDataRepository extends \Doctrine\ORM\EntityRepository
{
}
